### ISSUE TITLE
Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

### ISSUE THREAD

**Issue by bugbounted** [OsoianMarcel/telegram-openai-bot#1] opened 2023-01-06 20:09 UTC
Hi [Osoian Marcel](https://github.com/OsoianMarcel),
after deployed to render.com get error loop below on runtime :
```
Jan 6 11:27:17 PM  ==> Cloning from https://github.com/bugbounted/telegram-openai-bot...
Jan 6 11:27:18 PM  ==> Checking out commit d82c8186df0573735be15f6754ae5349497ca62c in branch main
Jan 6 11:27:20 PM  ==> Running build command 'go build -tags netgo -ldflags '-s -w' -o app'...
Jan 6 11:27:20 PM  go: downloading github.com/go-telegram-bot-api/telegram-bot-api/v5 v5.5.1
Jan 6 11:27:20 PM  go: downloading github.com/sashabaranov/go-gpt3 v0.0.0-20221216095610-1c20931ead68
Jan 6 11:27:26 PM  ==> Generating container image from build. This may take a few minutes...
Jan 6 11:28:19 PM  ==> Uploading build...
Jan 6 11:28:33 PM  ==> Build uploaded in 12s
Jan 6 11:28:34 PM  ==> Build successful 🎉
Jan 6 11:28:34 PM  ==> Deploying...
Jan 6 11:28:54 PM  ==> Starting service with './app'
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Start listener
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Worker #1 started
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Worker #0 started
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Worker #3 started
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Worker #2 started
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
Jan 6 11:28:55 PM  2023/01/06 19:58:55 Failed to get updates, retrying in 3 seconds...
Jan 6 11:28:58 PM  2023/01/06 19:58:58 Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
Jan 6 11:28:58 PM  2023/01/06 19:58:58 Failed to get updates, retrying in 3 seconds...
Jan 6 11:29:01 PM  2023/01/06 19:59:01 Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
Jan 6 11:29:01 PM  2023/01/06 19:59:01 Failed to get updates, retrying in 3 seconds...
Jan 6 11:29:04 PM  2023/01/06 19:59:04 Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
```

also my setting for deploy is :

```
Root Directory : cmd/tgbot
Build Command : go build -tags netgo -ldflags '-s -w' -o app
Start Command : ./app
```

envs :
```
tg_apitoken : telegram bot api token.
gpt_auth_token : openai api key.
tg_admin_chatid : bot owner chat id (used for feedback command).
```

waiting for your response
finest regards

**Comment by OsoianMarcel** [comment] 2023-01-06 20:46
Hello,

According to Telegram Bot API, the method [getUpdates](https://core.telegram.org/bots/api#getUpdates) (used in current project) will not work if an outgoing Webhook is set up.

Your logs are self-explanatory:
```
Conflict: can't use getUpdates method while Webhook is active; use deleteWebhook to delete the webhook first
```

I see 2 solutions:

1. Remove the Webhook from your current bot by using the method [deleteWebhook](https://core.telegram.org/bots/api#deletewebhook) method. 
2. Create and use a new bot (which by default does not have a Webhook).

To remove the Webhook from your bot try to call this URL https://api.telegram.org/bot{BOT_APITOKEN}/deleteWebhook?drop_pending_updates=true
Where `{BOT_APITOKEN}` is your Bot API Token.

**Comment by bugbounted** [comment] 2023-01-06 21:20
Hello again , 
now bot working but deploy is on progress & not finished
I think deploy failed after long time stay .
now deploy is failed but bot is work =))
regards

**Comment by bugbounted** [comment] 2023-01-06 21:27
bro , bot is down after 1 minute :(
please make changes on code to run after deploy process.
or make dockerfile in root to easily deployable to serverless paas like railway.
waiting for your commit/s.
regards

**Comment by OsoianMarcel** [comment] 2023-01-06 21:47
Please provide more information (more logs, info about your environment).
What do you mean by saying "deploy"?

I am running this software on a small Raspberry Pi computer for more than 2 days, and it works ok (the link to the bot is on README.md).
It also works fine on my MacBook.

I feel that something is wrong with your environment.

Currently, I am busy, and have no time to create a docker image.
But it's a good idea, and I'll take that into account.

I will also integrate the Webhook validation logic and warn users to remove it before using this software.

**Comment by OsoianMarcel** [comment] 2023-01-09 08:08
I'm closing this issue due to missing the information about the issue. Feels like the problem is related to the environment where the software is running and not the software itself.

**Closed as completed by OsoianMarcel** 2023-01-09 08:08 UTC
